My pull requestes
WALWALASAFI/survey-form pull request #1
Opened 2024-05-17 15:35 UTC by WALWALASAFI

Students survey analysis for feedback and insights.

2024-05-17 15:55 UTC, ahzamir commented
Hey @WALWALASAFI 
- You have some linters issues, always solve your linters and then submit your project for review.
- I can not provide you feedback till you don't solve the errors.

2024-05-18 04:38 UTC, WALWALASAFI commented
ok, sir

2024-05-19 19:14 UTC, WALWALASAFI commented
I have fixed the linter dear sir,

2024-05-21 05:21 UTC, WALWALASAFI commented
i have opened it sir

2024-05-21 05:25 UTC, WALWALASAFI commented
@ahzamir

2024-05-21 11:11 UTC, ahzamir requested changes
### Hi @WALWALASAFI 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Copy your HTML file code and paste it to the freecodecamp website survey form project to see which requirements your project is missing solve those missing requirements and mention me here using @ahzamir to re-review your project.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Survey Form and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-21 11:13 UTC, ahzamir requested changes
### Hi @WALWALASAFI 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Check the Inline comments below.
- Copy your HTML file code and paste it to the freecodecamp website survey form project to see which requirements your project is missing solve those missing requirements and mention me here using @ahzamir to re-review your project.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
❌ You have followed and completed the Survey Form and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-21 11:13 UTC, ahzamir commented on index.html
Your codes are not alligned correctly and are not clean try to make their spacing right.
- [**Suggession**] - On your HTML file, at the bottom right side of your vscode click on `Spaces`  then click on `Index using spaces`, and then select `2` from there. Then align your components according to the 2 spaces.
- Example:
```
<div>
  <p>...</p>
  <h1>.... </h1>
  <img ... />
</div>
```

2024-05-24 11:33 UTC, WALWALASAFI commented
Hi dear sir, 
i hope ur fine and doing great.
the code have been checked and accepted in free code camp 
also, it does not have any linter error.
finally is there anything remind for approving of the project.
kindly waiting for the feedback to make it correct as early as i can. 
![Uploading survey form.png…]()

2024-05-24 11:35 UTC, WALWALASAFI commented
Hi dear sir,
i hope ur fine and doing great.
the code have been checked and accepted in free code camp
also, it does not have any linter error.
finally is there anything remind for approving of the project.
kindly waiting for the feedback to make it correct as early as i can.
Uploading survey form.png…
@ahzamir 
@ahzia

2024-05-24 12:19 UTC, ahzamir requested changes
### Hi @WALWALASAFI 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- Although your code passes all the checks on freecodecamp website, but your HTML code is not clean please check the comments below for more details.

# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed and completed the Survey Form and all requirements.
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
❌ Your code is clean

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-24 12:19 UTC, ahzamir commented on index.html
> +</head>
- Clean your code for this part

2024-05-24 12:19 UTC, ahzamir commented on index.html
> +<form id="survey-form">
- Clean here

2024-05-24 12:19 UTC, ahzamir commented on index.html
> +</form>
- Here is clean just all of them should be two spaces ahead.

2024-05-24 12:19 UTC, ahzamir commented on index.html
> +  <form id="survey-form">
- Remove this

2024-05-25 05:35 UTC, WALWALASAFI commented
hi sir, 
i hope ur fine .
i did whatever u said , i cleaned unneccessary code and give 2 space ahead.
@ahzamir

2024-05-25 10:35 UTC, ahzamir requested changes
@WALWALASAFI 

- Still your code spacing is not right, try to get help from your partner.

2024-05-26 03:33 UTC, WALWALASAFI commented
Hi dear sir, 
i give space correctly. trust me sir i asked from my partner but she doesnt have any idea. so i looked up and tried much.
inshallah the code  will be correct and cleaned in this time.
@ahzamir

2024-05-26 12:52 UTC, ahzamir commented
> Hi dear sir, i give space correctly. trust me sir i asked from my partner but she doesnt have any idea. so i looked up and tried much. inshallah the code will be correct and cleaned in this time. @ahzamir

- Well done now it's correct.

2024-05-26 12:53 UTC, ahzamir approved these changes
### Hi @WALWALASAFI 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Survey Form project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-05-26 13:17 UTC, WALWALASAFI commented
thanks a bunch dear sir🙏🙏💜

2024-05-26 13:17 UTC, merged